from storage.memory_repository import fts_search_memories, fts_search_memories_scoped
from storage.memory_repository import list_memories as list_memories_unscoped
from storage.memory_repository import list_memories_scoped


def list_memories(
    db,
    *,
    agent_id,
    limit,
    offset,
    shared_only,
    private_only,
    visibility,
    owner_agent_id,
    status,
    run_id,
    tag,
    min_confidence,
    updated_since,
    recency_half_life_hours,
    metadata_key,
    metadata_value,
    metadata_value_type,
):
    if agent_id:
        return list_memories_scoped(
            db,
            agent_id=agent_id,
            limit=limit,
            offset=offset,
            shared_only=shared_only,
            private_only=private_only,
            visibility=visibility,
            owner_agent_id=owner_agent_id,
            status=status,
            run_id=run_id,
            tag=tag,
            min_confidence=min_confidence,
            updated_since=updated_since,
            metadata_key=metadata_key,
            metadata_value=metadata_value,
            metadata_value_type=metadata_value_type,
            recency_half_life_hours=recency_half_life_hours,
        )
    return list_memories_unscoped(
        db,
        limit=limit,
        offset=offset,
        visibility=visibility,
        owner_agent_id=owner_agent_id,
        status=status,
        run_id=run_id,
        tag=tag,
        min_confidence=min_confidence,
        updated_since=updated_since,
        metadata_key=metadata_key,
        metadata_value=metadata_value,
        metadata_value_type=metadata_value_type,
        recency_half_life_hours=recency_half_life_hours,
    )


def recall_memories(
    db,
    *,
    topic,
    agent_id,
    limit,
    offset,
    shared_only,
    private_only,
    visibility,
    owner_agent_id,
    status,
    run_id,
    tag,
    min_confidence,
    updated_since,
    recency_half_life_hours,
    metadata_key,
    metadata_value,
    metadata_value_type,
):
    safe_topic = topic.replace('"', "")
    if agent_id:
        return fts_search_memories_scoped(
            db,
            f'"{safe_topic}"',
            agent_id,
            limit=limit,
            offset=offset,
            shared_only=shared_only,
            private_only=private_only,
            visibility=visibility,
            owner_agent_id=owner_agent_id,
            status=status,
            run_id=run_id,
            tag=tag,
            min_confidence=min_confidence,
            updated_since=updated_since,
            recency_half_life_hours=recency_half_life_hours,
            metadata_key=metadata_key,
            metadata_value=metadata_value,
            metadata_value_type=metadata_value_type,
        )
    return fts_search_memories(
        db,
        f'"{safe_topic}"',
        limit=limit,
        offset=offset,
        visibility=visibility,
        owner_agent_id=owner_agent_id,
        status=status,
        run_id=run_id,
        tag=tag,
        min_confidence=min_confidence,
        updated_since=updated_since,
        recency_half_life_hours=recency_half_life_hours,
        metadata_key=metadata_key,
        metadata_value=metadata_value,
        metadata_value_type=metadata_value_type,
    )


def search_memories(
    db,
    *,
    q,
    agent_id,
    limit,
    offset,
    shared_only,
    private_only,
    visibility,
    owner_agent_id,
    status,
    run_id,
    tag,
    min_confidence,
    updated_since,
    recency_half_life_hours,
    metadata_key,
    metadata_value,
    metadata_value_type,
):
    safe_q = q.replace('"', "")
    if agent_id:
        return fts_search_memories_scoped(
            db,
            f'"{safe_q}"',
            agent_id,
            limit=limit,
            offset=offset,
            shared_only=shared_only,
            private_only=private_only,
            visibility=visibility,
            owner_agent_id=owner_agent_id,
            status=status,
            run_id=run_id,
            tag=tag,
            min_confidence=min_confidence,
            updated_since=updated_since,
            recency_half_life_hours=recency_half_life_hours,
            metadata_key=metadata_key,
            metadata_value=metadata_value,
            metadata_value_type=metadata_value_type,
        )
    return fts_search_memories(
        db,
        f'"{safe_q}"',
        limit=limit,
        offset=offset,
        visibility=visibility,
        owner_agent_id=owner_agent_id,
        status=status,
        run_id=run_id,
        tag=tag,
        min_confidence=min_confidence,
        updated_since=updated_since,
        recency_half_life_hours=recency_half_life_hours,
        metadata_key=metadata_key,
        metadata_value=metadata_value,
        metadata_value_type=metadata_value_type,
    )
